"""Canonical example inputs, so users (and the web UI) can try both branches in one click."""

from __future__ import annotations

import csv
import logging

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from app.jobs.constants import SAMPLE_FILENAMES
from app.jobs.schemas import SampleFile, SampleRegion, SignalSample
from app.schemas import SampleSequenceResponse

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/samples", tags=["samples"])

# First 151 nt of the example sequence from the MultiRM README. This is also the golden
# fixture in tests/fixtures/golden_multirm_151nt/ (hard-coded here so the server never
# reads from tests/ at runtime). Upstream reports 22 significant sites at alpha=0.05.
SAMPLE_SEQUENCE = (
    "GGGGCCGTGGATACCTGCCTTTTAATTCTTTTTTATTCGCCCATCGGGGCCGCGGATACCTGCTTTTTATTTTTTTTTCCTTAGCCC"
    "ATCGGGGTATCGGATACCTGCTGATTCCCTTCCCCTCTGAACCCCCAACACTCTGGCCCATCGG"
)

SAMPLE = SampleSequenceResponse(
    name="multirm_readme_151nt",
    description=(
        "First 151 nt of the example sequence from the MultiRM README; 22 sites at alpha=0.05"
    ),
    sequence=SAMPLE_SEQUENCE,
    length=len(SAMPLE_SEQUENCE),
    source_url="https://github.com/Tsedao/MultiRM",
)

SIGNAL_SAMPLE_NAME = "synthetic_rna004_3tx"
SIGNAL_SAMPLE_DESCRIPTION = (
    "SYNTHETIC RNA004-like direct-RNA reads (not real sequencing data), generated by "
    "scripts/make_signal_sample.py with a fixed seed: 3 transcripts - tx_A (40 reads), "
    "tx_B (36 reads) and tx_C (12 reads, below the 30-read coverage threshold, so DirectRM "
    "skips it) - about 1.4 MB in total, dorado move-table convention."
)
SAMPLE_NOT_INSTALLED = "The sample data set is not installed on this server."


@router.get("/sequence", response_model=SampleSequenceResponse, summary="Example sequence")
def get_sample_sequence() -> SampleSequenceResponse:
    """Return a ready-to-submit example sequence for `POST /api/predict/sequence`."""
    return SAMPLE


def _read_regions(path) -> list[SampleRegion]:
    try:
        with open(path, newline="", encoding="utf-8") as fh:
            return [
                SampleRegion(
                    seqnames=row["seqnames"],
                    start=int(row["start"]),
                    end=int(row["end"]),
                    width=int(row["width"]),
                    strand=row["strand"],
                )
                for row in csv.DictReader(fh)
            ]
    except (OSError, KeyError, ValueError, TypeError) as exc:
        log.warning("could not parse sample regions %s: %s", path, exc)
        return []


@router.get(
    "/signal",
    response_model=SignalSample,
    summary="Example nanopore data set (synthetic)",
    responses={404: {"description": "Sample files not installed"}},
)
def get_sample_signal(request: Request) -> SignalSample:
    """Describe the built-in synthetic pod5/BAM/reference/regions set. Download the files
    from `files[].url`, or run it directly with `POST /api/jobs/signal/sample`.
    """
    sample_dir = request.app.state.settings.sample_dir
    paths = {slot: sample_dir / name for slot, name in SAMPLE_FILENAMES.items()}
    if not all(p.is_file() for p in paths.values()):
        raise HTTPException(status_code=404, detail=SAMPLE_NOT_INSTALLED)
    files = [
        SampleFile(
            slot=slot,
            filename=path.name,
            bytes=path.stat().st_size,
            url=f"/api/samples/signal/files/{path.name}",
        )
        for slot, path in paths.items()
    ]
    return SignalSample(
        name=SIGNAL_SAMPLE_NAME,
        description=SIGNAL_SAMPLE_DESCRIPTION,
        kit="RNA004",
        files=files,
        source="synthetic",
        regions=_read_regions(paths["regions"]),
    )


@router.get(
    "/signal/files/{filename}",
    summary="Download one sample file",
    response_class=FileResponse,
    responses={200: {"content": {"application/octet-stream": {}}}, 404: {}},
)
def get_sample_signal_file(filename: str, request: Request) -> FileResponse:
    if filename not in SAMPLE_FILENAMES.values():
        raise HTTPException(status_code=404, detail="No such sample file.")
    path = request.app.state.settings.sample_dir / filename
    if not path.is_file():
        raise HTTPException(status_code=404, detail=SAMPLE_NOT_INSTALLED)
    return FileResponse(
        path,
        filename=filename,
        media_type="application/octet-stream",
        headers={"Cache-Control": "public, max-age=3600"},
    )
