"""Integrity checks for the synthetic nanopore sample data in ``app/samples/signal``.

The files are generated by ``scripts/make_signal_sample.py`` (see its docstring and the
README in the sample directory). These tests make sure that what is committed is what the
manifest says, that the pod5 and the BAM describe the same reads, and that every BAM record
satisfies the move-table invariants Remora checks before DirectRM can extract features.
"""

from __future__ import annotations

import csv
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import pod5
import pysam
import pytest

REPO = Path(__file__).resolve().parents[1]
SAMPLE_DIR = REPO / "app" / "samples" / "signal"
GENERATOR = REPO / "scripts" / "make_signal_sample.py"

FILES = {
    "pod5": "sample.pod5",
    "bam": "sample_sorted.bam",
    "bai": "sample_sorted.bam.bai",
    "reference": "sample_reference.fa",
    "fai": "sample_reference.fa.fai",
    "regions": "sample_regions.csv",
    "readme": "README.md",
}
EXPECTED_READS = {"tx_A": 40, "tx_B": 36, "tx_C": 12}
EXPECTED_REGIONS = [
    {"seqnames": "tx_A", "start": "60", "end": "300", "width": "241", "strand": "+"},
    {"seqnames": "tx_B", "start": "80", "end": "320", "width": "241", "strand": "+"},
    {"seqnames": "tx_C", "start": "50", "end": "250", "width": "201", "strand": "+"},
]
MAX_TOTAL_BYTES = 2_000_000


def _load_generator():
    """Import scripts/make_signal_sample.py without requiring scripts/ to be a package."""
    spec = importlib.util.spec_from_file_location("make_signal_sample", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolve string annotations through sys.modules[cls.__module__]
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def manifest() -> dict:
    return json.loads((SAMPLE_DIR / "MANIFEST.json").read_text())


@pytest.fixture(scope="module")
def bam_records() -> list[pysam.AlignedSegment]:
    with pysam.AlignmentFile(str(SAMPLE_DIR / FILES["bam"]), "rb") as bam:
        return list(bam.fetch(until_eof=True))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_manifest_lists_every_file_with_matching_size_and_sha256(manifest):
    assert set(manifest["files"]) == set(FILES.values())
    for name, entry in manifest["files"].items():
        path = SAMPLE_DIR / name
        assert path.is_file(), name
        assert path.stat().st_size == entry["bytes"], name
        assert _sha256(path) == entry["sha256"], name
    assert sum(e["bytes"] for e in manifest["files"].values()) < MAX_TOTAL_BYTES
    assert manifest["synthetic"] is True
    assert manifest["generator"]["args"]["layout"] == "rna_raw"
    assert manifest["expected_reads"] == {**EXPECTED_READS, "total": 88}


def test_pod5_content_digest_matches_manifest(manifest):
    gen = _load_generator()
    digest = gen.pod5_content_digest(SAMPLE_DIR / FILES["pod5"])
    assert digest == manifest["files"][FILES["pod5"]]["content_sha256"]
    assert manifest["pod5_content_digest"]["recipe"] == gen.POD5_DIGEST_RECIPE


def test_pod5_is_readable_by_the_worker_pod5_version(manifest):
    # pod5 0.3.46 introduced POD5 v6 (32-bit channel field). The worker (Python 3.10,
    # lib-pod5 0.3.47) reads v6 fine; the bundled sample stays a v5 file so that the pod5
    # 0.3.35 pinned in tools/Dockerfile.subset (and any other older reader) can open it
    # (docs/signal-branch.md section 11, item 10). The generator enforces the older writer.
    written_with = tuple(int(x) for x in manifest["generator"]["versions"]["pod5"].split("."))
    assert written_with <= (0, 3, 45)


def test_pod5_and_bam_describe_the_same_88_reads(bam_records):
    with pod5.Reader(SAMPLE_DIR / FILES["pod5"]) as reader:
        pod5_reads = {str(rec.read_id): rec for rec in reader.reads()}
        bam_ids = {rec.query_name for rec in bam_records}
        assert len(bam_records) == len(bam_ids) == 88
        assert set(pod5_reads) == bam_ids
        for rec in pod5_reads.values():
            assert rec.signal.dtype.name == "int16"
            assert rec.run_info.sample_rate == 4000
            assert rec.run_info.sequencing_kit == "sqk-rna004"
            assert rec.run_info.flow_cell_product_code == "FLO-MIN004RA"
        # ns (end of basecalled signal) must lie inside the stored signal
        for rec in bam_records:
            assert rec.get_tag("ns") <= pod5_reads[rec.query_name].signal.size


def test_every_bam_record_satisfies_the_remora_move_table_invariants(bam_records):
    for rec in bam_records:
        for tag in ("mv", "ts", "ns", "MD", "NM"):
            assert rec.has_tag(tag), f"{rec.query_name} lacks {tag}"
        mv = rec.get_tag("mv")
        stride, moves = int(mv[0]), list(mv[1:])
        ts, ns = rec.get_tag("ts"), rec.get_tag("ns")
        assert stride == 5
        assert len(moves) == (ns - ts) // stride, rec.query_name
        assert sum(moves) == rec.query_length == len(rec.query_sequence), rec.query_name
        assert moves[0] == 1
        assert rec.flag == 0 and rec.mapping_quality == 60
        assert not rec.is_secondary and not rec.is_supplementary
        # MD/NM agree with the reference sequence embedded through the MD tag
        ref = rec.get_reference_sequence().upper()
        aligned_query = rec.query_alignment_sequence
        assert len(ref) == len(aligned_query) == rec.reference_length
        assert sum(a != b for a, b in zip(ref, aligned_query)) == rec.get_tag("NM") <= 2
        assert all(5 <= q <= 29 for q in rec.query_qualities)


def test_reads_per_transcript_and_full_region_coverage(bam_records):
    regions = {r["seqnames"]: (int(r["start"]), int(r["end"])) for r in EXPECTED_REGIONS}
    counts = {name: 0 for name in EXPECTED_READS}
    for rec in bam_records:
        counts[rec.reference_name] += 1
        start, end = regions[rec.reference_name]
        # 0-based half-open alignment span must contain the 1-based inclusive region
        assert rec.reference_start <= start - 1 and rec.reference_end >= end
    assert counts == EXPECTED_READS


def test_regions_csv_has_five_columns_and_three_rows():
    with open(SAMPLE_DIR / FILES["regions"], newline="") as fh:
        reader = csv.DictReader(fh)
        assert reader.fieldnames == ["seqnames", "start", "end", "width", "strand"]
        rows = list(reader)
    assert rows == EXPECTED_REGIONS
    for row in rows:
        assert int(row["width"]) == int(row["end"]) - int(row["start"]) + 1


def test_reference_contigs_match_bam_header():
    with pysam.FastaFile(str(SAMPLE_DIR / FILES["reference"])) as fasta:
        contigs = dict(zip(fasta.references, fasta.lengths))
        for name, seq in ((n, fasta.fetch(n)) for n in fasta.references):
            assert set(seq) <= set("ACGT"), name
            assert seq.endswith("A" * 20), name
    assert list(contigs) == ["tx_A", "tx_B", "tx_C"]
    assert all(500 <= length <= 600 for length in contigs.values())
    with pysam.AlignmentFile(str(SAMPLE_DIR / FILES["bam"]), "rb") as bam:
        assert dict(zip(bam.references, bam.lengths)) == contigs
        header = bam.header.to_dict()
    assert header["HD"]["SO"] == "coordinate"
    assert "SYNTHETIC" in header["RG"][0]["DS"]
    assert "SYNTHETIC" in header["PG"][0]["CL"]


def test_readme_states_synthetic_origin_and_licence():
    text = (SAMPLE_DIR / FILES["readme"]).read_text()
    for needle in ("synthetic", "CC0", "rna_raw", "20250831", "40 / 36 / 12", "reverse_signal"):
        assert needle in text, needle
